/**
 * 中考英语听力题库
 * 三维标签：grade(7/8/9) × type(A图片/B短对话/C长对话/D听写) × level(1基础/2进阶/3挑战)
 * A部分：听句子/对话选图片（emoji 图片表示）
 * B部分：听短对话选答案（四选一）
 * C部分：听长对话/独白选答案（四选一）
 * D部分：听写填空（填入缺失的单词）
 *
 * 字段说明：
 *   id, grade, type, level, audio(朗读文本), question(题干),
 *   options(选项数组), answer(正确索引), explain(解析)
 *   D部分额外：blanks(空缺词数组), sentence(完整句)
 */
const LISTENING = [
  // ============ A 部分：听句子/对话选图片 ============
  // --- 七年级 ---
  {id:'A7-1',grade:7,type:'A',level:1,
   audio:"Look! There is a cute cat under the table.",
   question:"What animal is under the table?",
   options:["🐶","🐱","🐰","🐦"],answer:1,explain:"句中提到 cat（猫），对应 🐱"},
  {id:'A7-2',grade:7,type:'A',level:1,
   audio:"My favorite fruit is the yellow banana.",
   question:"What fruit does the speaker like best?",
   options:["🍎","🍇","🍌","🍊"],answer:2,explain:"favorite fruit 是 banana（香蕉）🍌"},
  {id:'A7-3',grade:7,type:'A',level:1,
   audio:"It's rainy today. Don't forget your umbrella.",
   question:"How is the weather today?",
   options:["☀️","🌧️","❄️","🌪️"],answer:1,explain:"rainy 下雨，对应 🌧️"},
  {id:'A7-4',grade:7,type:'A',level:2,
   audio:"The boy in a red shirt is my brother Tom.",
   question:"What color is Tom's shirt?",
   options:["🔴","🔵","🟢","🟡"],answer:0,explain:"red shirt 红衬衫，对应红色 🔴"},
  {id:'A7-5',grade:7,type:'A',level:2,
   audio:"We usually have breakfast at seven in the morning.",
   question:"When do they have breakfast?",
   options:["🌅 7am","🌞 12pm","🌇 6pm","🌙 9pm"],answer:0,explain:"seven in the morning 早上七点"},
  // --- 八年级 ---
  {id:'A8-1',grade:8,type:'A',level:1,
   audio:"Lily is going to take a plane to Shanghai tomorrow.",
   question:"How will Lily travel?",
   options:["🚗","🚂","✈️","🚢"],answer:2,explain:"take a plane 坐飞机 ✈️"},
  {id:'A8-2',grade:8,type:'A',level:2,
   audio:"My father bought me a new basketball for my birthday.",
   question:"What gift did the father buy?",
   options:["⚽","🏀","🏈","⚾"],answer:1,explain:"basketball 篮球 🏀"},
  {id:'A8-3',grade:8,type:'A',level:2,
   audio:"The teacher asked us to open our books and read page ten.",
   question:"What should the students do?",
   options:["📖 翻书读","✍️ 写字","🗣️ 说话","👂 听讲"],answer:0,explain:"open books and read 翻开书阅读"},
  {id:'A8-4',grade:8,type:'A',level:3,
   audio:"It was so cold that the river turned into ice last night.",
   question:"What happened to the river?",
   options:["💧 流水","🧊 结冰","🌊 涨水","🐟 有鱼"],answer:1,explain:"turned into ice 结成冰 🧊"},
  {id:'A8-5',grade:8,type:'A',level:3,
   audio:"Look at the sign. We mustn't park our cars here.",
   question:"What does the sign mean?",
   options:["✅ 允许停车","🚫 禁止停车","🅿️ 收费停车","🔧 修理厂"],answer:1,explain:"mustn't park 禁止停车 🚫"},
  // --- 九年级 ---
  {id:'A9-1',grade:9,type:'A',level:2,
   audio:"The scientist won the Nobel Prize for his great discovery.",
   question:"Who is the speaker talking about?",
   options:["👨‍🏫 老师","👨‍🔬 科学家","👨‍🎨 画家","👨‍✈️ 飞行员"],answer:1,explain:"scientist 科学家"},
  {id:'A9-2',grade:9,type:'A',level:3,
   audio:"The bridge was built by the local people two hundred years ago.",
   question:"How old is the bridge?",
   options:["100年","200年","300年","50年"],answer:1,explain:"two hundred years ago 两百年前"},
  {id:'A9-3',grade:9,type:'A',level:3,
   audio:"Recycling paper can help save thousands of trees every year.",
   question:"What is the speaker mainly talking about?",
   options:["🌿 环保","💼 商业","🎓 教育","🏥 医疗"],answer:0,explain:"recycling / save trees 都关于环境保护 🌿"},

  // ============ B 部分：听短对话选答案 ============
  // --- 七年级 ---
  {id:'B7-1',grade:7,type:'B',level:1,
   audio:"W: Hi, Tom. What's your favorite subject? M: I like math best. It's interesting.",
   question:"What's Tom's favorite subject?",
   options:["English","Math","Chinese","Art"],answer:1,explain:"男士回答 math best"},
  {id:'B7-2',grade:7,type:'B',level:1,
   audio:"W: How do you go to school, Mike? M: I usually ride my bike.",
   question:"How does Mike go to school?",
   options:["By bus","By bike","On foot","By car"],answer:1,explain:"ride my bike 骑自行车"},
  {id:'B7-3',grade:7,type:'B',level:2,
   audio:"W: What time do you get up? M: I get up at six thirty every day.",
   question:"What time does the boy get up?",
   options:["6:00","6:15","6:30","7:00"],answer:2,explain:"six thirty 6:30"},
  {id:'B7-4',grade:7,type:'B',level:2,
   audio:"M: Can I help you? W: Yes, I'd like a cup of tea, please.",
   question:"What does the woman want?",
   options:["Coffee","Juice","Tea","Water"],answer:2,explain:"a cup of tea 一杯茶"},
  {id:'B7-5',grade:7,type:'B',level:1,
   audio:"W: Is this your pen? M: No, it isn't. Mine is blue.",
   question:"What color is the boy's pen?",
   options:["Red","Blue","Black","Green"],answer:1,explain:"Mine is blue 我的（笔）是蓝色"},
  // --- 八年级 ---
  {id:'B8-1',grade:8,type:'B',level:2,
   audio:"W: Did you watch the football match yesterday? M: Yes, our team won 3 to 1.",
   question:"What was the score?",
   options:["3-0","3-1","2-1","1-0"],answer:1,explain:"won 3 to 1 比分 3:1"},
  {id:'B8-2',grade:8,type:'B',level:2,
   audio:"M: How long have you learned English? W: For about five years.",
   question:"How long has the girl learned English?",
   options:["3 years","5 years","7 years","10 years"],answer:1,explain:"For about five years 约5年"},
  {id:'B8-3',grade:8,type:'B',level:3,
   audio:"W: What do you think of the movie? M: To be honest, it was a bit boring.",
   question:"What does the man think of the movie?",
   options:["Exciting","Boring","Funny","Great"],answer:1,explain:"a bit boring 有点无聊"},
  {id:'B8-4',grade:8,type:'B',level:3,
   audio:"M: Shall we meet at the school gate at 8? W: Let's make it half an hour earlier.",
   question:"What time will they meet?",
   options:["7:00","7:30","8:00","8:30"],answer:1,explain:"half an hour earlier 比8点早半小时 = 7:30"},
  {id:'B8-5',grade:8,type:'B',level:2,
   audio:"W: Why didn't you come to school yesterday? M: I had a bad cold and stayed in bed.",
   question:"Why was the boy absent?",
   options:["Headache","Stomachache","Cold","Fever"],answer:2,explain:"had a bad cold 重感冒"},
  // --- 九年级 ---
  {id:'B9-1',grade:9,type:'B',level:3,
   audio:"W: What do you want to be in the future? M: I dream of becoming an engineer like my father.",
   question:"What does the boy want to be?",
   options:["A doctor","An engineer","A teacher","A pilot"],answer:1,explain:"becoming an engineer 成为工程师"},
  {id:'B9-2',grade:9,type:'B',level:3,
   audio:"M: How much is this shirt? W: It was 200 yuan, but there's a 20% discount today.",
   question:"How much does the shirt cost now?",
   options:["160元","180元","200元","220元"],answer:0,explain:"200×0.8 = 160元"},
  {id:'B9-3',grade:9,type:'B',level:3,
   audio:"W: I heard you traveled to Beijing. How was it? M: Wonderful! I visited the Great Wall and the Palace Museum.",
   question:"Where did the man visit in Beijing?",
   options:["The Great Wall","The zoo","The park","The cinema"],answer:0,explain:"the Great Wall 长城"},
  {id:'B9-4',grade:9,type:'B',level:2,
   audio:"M: Are you free this weekend? W: I'm afraid not. I have to prepare for the exam.",
   question:"Why can't the woman go out this weekend?",
   options:["She's ill","She's busy with exam","She's traveling","She's working"],answer:1,explain:"prepare for the exam 准备考试"},
  {id:'B9-5',grade:9,type:'B',level:3,
   audio:"W: You look tired. Did you stay up late? M: Yes, I studied until midnight.",
   question:"Why is the man tired?",
   options:["He ran too much","He stayed up late","He ate too much","He slept too long"],answer:1,explain:"stay up late 熬夜"},

  // ============ C 部分：听长对话/独白选答案 ============
  {id:'C7-1',grade:7,type:'C',level:1,
   audio:"M: Mom, where is my schoolbag? W: It's on the sofa in the living room. M: And my English book? W: It's in your schoolbag. Don't forget your homework. M: OK. I'm going to school now. Bye! W: Bye! Have a good day!",
   question:"Where is the boy's English book?",
   options:["On the sofa","In the schoolbag","On the desk","In the bedroom"],answer:1,explain:"It's in your schoolbag 在书包里"},
  {id:'C7-2',grade:7,type:'C',level:2,
   audio:"W: Hello, Sam. This is Mary. What are you doing? M: I'm reading a story book. W: Would you like to play football with us? M: I'd love to, but I have to finish my homework first. W: OK. See you later.",
   question:"Why can't Sam play football now?",
   options:["He's reading","He's doing homework","He's sleeping","He's eating"],answer:1,explain:"have to finish my homework first 得先完成作业"},
  {id:'C8-1',grade:8,type:'C',level:2,
   audio:"W: Hi, Jack. You look happy. Any good news? M: Yes! I won first prize in the English speech contest. W: Congratulations! When was the contest? M: Last Friday. I practiced for two weeks. W: You worked hard. Your English is really good. M: Thanks. I read English every morning.",
   question:"When did Jack win the prize?",
   options:["Last Monday","Last Friday","Last Sunday","Yesterday"],answer:1,explain:"Last Friday 上周五"},
  {id:'C8-2',grade:8,type:'C',level:3,
   audio:"M: Hi, Anna. Long time no see. Where have you been? W: I went to Sanya with my family for a holiday. M: Wow! How was the weather there? W: It was sunny and warm. We swam in the sea every day. M: Did you take any photos? W: Of course. I'll show you later. M: That sounds wonderful. W: Yes, it was the best trip ever.",
   question:"What did Anna do in Sanya?",
   options:["Climbed mountains","Swam in the sea","Visited museums","Went shopping"],answer:1,explain:"We swam in the sea 在海里游泳"},
  {id:'C9-1',grade:9,type:'C',level:3,
   audio:"Good morning, everyone. Welcome to our school library. Let me introduce the rules. First, the library is open from 8 am to 6 pm every day. Second, you can borrow up to five books at a time, and keep them for two weeks. Third, please keep quiet. No eating or drinking here. Finally, return books on time, or you'll pay a fine. Enjoy your reading!",
   question:"How many books can a student borrow at a time?",
   options:["Three","Five","Ten","Unlimited"],answer:1,explain:"up to five books 最多5本"},
  {id:'C9-2',grade:9,type:'C',level:3,
   audio:"M: Sarah, I heard you're going to study abroad. W: Yes, in Canada. I'm really excited but also nervous. M: When will you leave? W: Next month. I've already booked the ticket. M: What will you study? W: Computer Science. I want to be a programmer. M: That's great. I'll miss you. W: Me too. Let's keep in touch by email.",
   question:"What will Sarah study in Canada?",
   options:["Medicine","Computer Science","Business","Art"],answer:1,explain:"Computer Science 计算机科学"},
  {id:'C9-3',grade:9,type:'C',level:3,
   audio:"Boys and girls, may I have your attention, please? Our school will hold a Sports Day next Friday. There will be many events: running, jumping, and team games. Everyone should take part. Please sign up at the office before Wednesday. Remember to wear sports clothes and bring water. Let's make it a great day! Thank you.",
   question:"When is the Sports Day?",
   options:["This Friday","Next Friday","Next Wednesday","Next Monday"],answer:1,explain:"next Friday 下周五"},

  // ============ D 部分：听写填空 ============
  {id:'D7-1',grade:7,type:'D',level:1,
   audio:"My name is Tom. I am twelve years old. I have a sister. Her name is Lily. We are both students.",
   sentence:"My name is Tom. I am _____ years old. I have a _____. Her name is Lily.",
   blanks:["twelve","sister"],answer:["twelve","sister"],explain:"twelve 十二；sister 姐妹"},
  {id:'D7-2',grade:7,type:'D',level:1,
   audio:"I get up at six thirty every morning. Then I eat breakfast and go to school by bus.",
   sentence:"I get up at _____ thirty every morning. Then I eat breakfast and go to school by _____.",
   blanks:["six","bus"],answer:["six","bus"],explain:"six thirty 六点半；by bus 乘公交"},
  {id:'D7-3',grade:7,type:'D',level:2,
   audio:"There are four seasons in a year. Spring is warm. Summer is hot. Autumn is cool. Winter is cold.",
   sentence:"There are _____ seasons in a year. Spring is _____. Summer is hot.",
   blanks:["four","warm"],answer:["four","warm"],explain:"four 四；warm 温暖的"},
  {id:'D8-1',grade:8,type:'D',level:2,
   audio:"My hobby is reading. I have collected more than two hundred books. Reading makes me happy and clever.",
   sentence:"My hobby is reading. I have collected more than two _____ books. Reading makes me happy and _____.",
   blanks:["hundred","clever"],answer:["hundred","clever"],explain:"two hundred 两百；clever 聪明的"},
  {id:'D8-2',grade:8,type:'D',level:2,
   audio:"Last weekend, my family went to the beach. The weather was sunny. We swam and built sandcastles.",
   sentence:"Last weekend, my family went to the _____. The weather was _____. We swam and built sandcastles.",
   blanks:["beach","sunny"],answer:["beach","sunny"],explain:"beach 海滩；sunny 晴朗的"},
  {id:'D8-3',grade:8,type:'D',level:3,
   audio:"Protecting the environment is everyone's duty. We should plant more trees and reduce plastic use.",
   sentence:"Protecting the _____ is everyone's duty. We should plant more trees and reduce _____ use.",
   blanks:["environment","plastic"],answer:["environment","plastic"],explain:"environment 环境；plastic 塑料"},
  {id:'D9-1',grade:9,type:'D',level:3,
   audio:"Technology has changed our lives greatly. With smartphones, we can communicate with people anywhere in the world.",
   sentence:"Technology has changed our _____ greatly. With smartphones, we can communicate with people anywhere in the _____.",
   blanks:["lives","world"],answer:["lives","world"],explain:"lives 生活；world 世界"},
  {id:'D9-2',grade:9,type:'D',level:3,
   audio:"The Internet makes it easy to get information. However, we must be careful about what we believe online.",
   sentence:"The Internet makes it easy to get _____. However, we must be careful about what we _____ online.",
   blanks:["information","believe"],answer:["information","believe"],explain:"information 信息；believe 相信"},
  {id:'D9-3',grade:9,type:'D',level:3,
   audio:"Good habits lead to success. Early to bed and early to rise makes a man healthy and wise.",
   sentence:"Good habits lead to _____. Early to bed and early to rise makes a man healthy and _____.",
   blanks:["success","wise"],answer:["success","wise"],explain:"success 成功；wise 智慧的"}
];

if (typeof window !== 'undefined') {
  // 合并扩充题库
  var ALL_LISTENING = LISTENING.slice();
  if (window.LISTENING_EXTRA) {
    ALL_LISTENING = ALL_LISTENING.concat(window.LISTENING_EXTRA);
  }
  window.LISTENING = ALL_LISTENING;
}
